server:
  port : 8088
  servlet:
    context-path: /
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/task_generator
    username: postgres
    password: postgres
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
